import { DM_Sans } from "next/font/google";
import "./globals.css";

const dm = DM_Sans ({ 
  subsets: ["latin"], 
  display: 'swap',
});

export const metadata = {
  title: "Tamarinthian",
  description: "Generated by tam",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={dm.className}>{children}</body>
    </html>
  );
}
